### ISSUE TITLE
'Overlay' object has no attribute 'set_overlay_pass_through'

### ISSUE THREAD

**Issue by drazioti** [CSD-FOSS-Team/genume#62]
$ python3 -m genume
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/draziotis/Documents/genume/genume/__main__.py", line 21, in <module>
    main()
  File "/home/draziotis/Documents/genume/genume/genume.py", line 26, in main
    gui.main()
  File "/home/draziotis/Documents/genume/genume/view/main.py", line 14, in main
    MainWindow()
  File "/home/draziotis/Documents/genume/genume/view/main.py", line 43, in __init__
    self.add(self.generate_main_view(reg))
  File "/home/draziotis/Documents/genume/genume/view/main.py", line 124, in generate_main_view
    main_view.set_overlay_pass_through(refresh_button, True)
AttributeError: 'Overlay' object has no attribute 'set_overlay_pass_through'

If I comment line 124 in /genume/genume/view/main.py, the program starts normally.
python version : 3.4.2
GTK version : 3.14.5-1+deb8u

**Comment by MaanooAk** [comment]
`set_overlay_pass_through` is since GTK 3.18, so we should find an alternative (I will look into it in the next days)

**Comment by drazioti** [comment]
Well, the refresh button is also working for me. Maybe we should close the ticket.

**Comment by MaanooAk** [comment]
`set_overlay_pass_through` will be removed (for now)
